### ISSUE TITLE
Can not display highchart after fetching data from api server

### ISSUE THREAD

**Issue by darkhorse315** [highcharts/highcharts-android#109]
I am displaying the highchart with the data from the server.
I am using retrofit android API library.
After I get the data, the highchart wasn't shown.

This is my logcat:

...
Landroid/view/textclassifier/logging/SmartSelectionEventTracker$SelectionEvent; (light greylist, reflection)
W/horse.networki: Accessing hidden field Lsun/misc/Unsafe;->theUnsafe:Lsun/misc/Unsafe; (light greylist, reflection)
E/HIChartView: HIOptions not attached. Chart won't render without options.
D/EGL_emulation: eglMakeCurrent: 0xecd85480: ver 3 0 (tinfo 0xecd83740)
D/EGL_emulation: eglMakeCurrent: 0xecd85480: ver 3 0 (tinfo 0xecd83740)
D/EGL_emulation: eglMakeCurrent: 0xecd85480: ver 3 0 (tinfo 0xecd83740)
W/cr_CrashFileManager: /data/user/0/com.darkhorse.networkit/cache/WebView/Crash Reports does not exist or is not a directory

**Comment by soommy12** [comment]
Hello @lovelyjy315 ! There was a lot of questions like this already. This is happening because Android draws its views before you get a response from your API - the same applies to `HIChartView`. First, you need to setup chart with empty options, then update them with your API response data and set options again. Check out [this ](https://github.com/highcharts/highcharts-android/issues/35)question or other issues (closed ones) - the answers there will definitely help you.

**Comment by darkhorse315** [comment]
Thanks. I solved the issue.
