### ISSUE TITLE
Drilldown event triggers but does not provide any property

### ISSUE THREAD

**Issue by Rohaan1691** [highcharts/highcharts-android#114]
I am having trouble with the following code I am trying to get "category" or any other property possible on the drill-down event but that is not happening. I get the event but the properties are "nil" in all of the cases.

Following is my code:

 val event = HIEvents()
        event.drilldown = HIFunction(HIConsumer {  p0:HIChartContext ->
            println(p0.getProperty("events.seriesOptions"))
        }, arrayOf("events.category", "events.seriesOptions", "events.point.x", "events.point.y", "events.point.drilldown", "events.drilldown"))

        chart.events = event

What I eventually want to achieve is dynamic minWidth on different levels of drill-down depending on the number of categories on the xAxis

**Comment by MikolajMichalczak** [comment]
Hi everyone,

I'm pleased to inform you that following the latest version (11.4.7), functions that require passing a reference via an argument in the original framework are now supported on Android.

Regarding the mentioned issue, please pass the following parameters:
```kotlin
val event = HIEvents()
event.drilldown = HIFunction(HIConsumer { f: HIChartContext ->
    val category = f.getProperty("category")
    val seriesOptions = f.getProperty("seriesOptions")
    val pointX = f.getProperty("point.x")
    val pointY = f.getProperty("point.y")
    val pointDrilldown = f.getProperty("point.drilldown")
    val drilldown = f.getProperty("drilldown")
}, arrayOf("category", "seriesOptions", "point.x", "point.y", "point.drilldown", "drilldown"))
chart.events = event
```
Thank you for your patience, and we hope this enhancement will improve your experience.

Since this feature is now implemented, I am closing this issue. If you have any further questions or feedback, please feel free to reopen the ticket.
