### ISSUE TITLE
Question about added permissions

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#130]
Please explain why the Highcharts library adds these permissions:
`android.permission.DOWNLOAD_WITHOUT_NOTIFICATION`
`android.permission.READ_EXTERNAL_STORAGE`
`android.permission.WRITE_EXTERNAL_STORAGE`

I'd like to know which of those could be safely removed from the resulting (merged) manifest file

**Comment by soommy12** [comment]
Hi @adenisyuk ! Those permissions are here for chart export feature.

**Comment by kainjinez** [comment]
@soommy12 Hello. Can you provide more information with exporting feature in Android App? 
And If I don't want to use that feature, how can I remove that permission from Manifest? 
Because it looks a bit risky if app can download anything without user's permission. 
Thanks.

**Comment by soommy12** [comment]
hi @kainjinez the export feature is creating an image of the chart saving it to local storage and then letting you send it via another app reading that image from app storage. It's true that those permissions are considered dangerous but they were added because of some other users' feedback. You can remove it from the merged manifest file of your app. We will rethink our approach for library embedded permissions in future releases. Thanks for your input!
