### ISSUE TITLE
Cannot pull properties from selection event function (Uncaught TypeError: Converting circular structure to JSON)

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#132]
Hi there,

I'm trying to detect the chart selection with `chart.event.selection function`: 

```
hiOptions.chart=HIChart().apply{
	events=HIEvents().apply{
		selection=HIFunction(
			HIConsumer{
				//function body
				//data needed here:
				// xAxis[0].min
				// xAxis[0].max
				// yAxis[0].min
				// yAxis[0].max
			},
			arrayOf("xAxis", "yAxis")
		)
	}
}
```

And here is what is happening when the user zooms in a chart:
```
E/Highcharts: Uncaught TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'c.Chart'
        |     property 'navigation' -> object with constructor 'Object'
        |     property 'updates' -> object with constructor 'Array'
        |     index 0 -> object with constructor 'Object'
        --- property 'context' closes the circle
```

Please note, that we have zoom type set to `xy`, thus detecting zoom factor with `afterSetExtremes` event function is no longer possible.

Could you please explain what is the proper way to get `event` data in a `HIConsumer` in the aforementioned scenario

**Comment by soommy12** [comment]
Hi @adenisyuk ! Some values inside chart options are not possible to get due to `circural-references` which are not parsable back to Java.
First of all, when you're working on variable withdrawn from the chart, you should use `getProperty()` method inside the callback.
Another thing is that you should never refer to that property as an object. The best practice is to withdraw the specific data instead of an object (like `xAxis` here). Due to the type of property is unknown you should cast the property to a class you reckon to get.

Anything from [here](https://api.highcharts.com/class-reference/Highcharts.Chart) from members which is not a primitive type will give you that error or it will be just hard to get inside the native Java code. I suggest you getting min/max value from your `Axis` object because it has simpler to get [numeric value](https://api.highcharts.com/class-reference/Highcharts.Axis#max) already.

**Comment by adenisyuk** [comment]
Thank you for your reply, @soommy12 !

I've tried to get values as you proposed:
```
HIFunction(
	HIConsumer {
		val xMin = it.getProperty("xAxis[0].min") as Double?
		val xMax = it.getProperty("xAxis[0].max") as Double?

		val yMin = it.getProperty("yAxis[0].min") as Double?
		val yMax = it.getProperty("yAxis[0].max") as Double?

		Timber.e("x: $xMin  $xMax   y: $yMin  $yMax")
	},
	arrayOf("xAxis[0].min", "xAxis[0].max", "yAxis[0].min", "yAxis[0].max")
)
```

And the printed values are always null. 
Have you tried your solution, does it work for you?
Please correct me on what I am doing wrong.
Thank you

**Comment by soommy12** [comment]
What kind of callback are you using on the chart object?

**Comment by adenisyuk** [comment]
@soommy12 ,
Please take a look at my first message in this thread.

It's a `public HIFunction(HIConsumer<HIChartContext> var1, String[] var2)` constructor of `HIFunction` if if I've got your question right

**Comment by soommy12** [comment]
I've meant the function where are you passing `HIFunction` but it is already in your code. You are using `selection`, I've missed it. that  Gonna investigate.

**Comment by soommy12** [comment]
Unfortunately, passing values which are inside an array into callback is a little bit clunky. You should use dots. Change `yAxis[0].min` to `yAxis.0.min` and so on. Should work like a charm.

**Comment by adenisyuk** [comment]
Wow. What a surprise!
I think it should be mention in your docs (or at least in Readme.md of this repo).

Thank you for your help, it works now.

BTW, this function (`selection`) works differently with the Android library, comparing to the web. 
Axis's min and max values  are always non-null on Android, while on the web they are nulls when the chart is not zoomed: https://jsfiddle.net/5zvcbw6e/1/

Anyway, with this info on how to pull JS arrays data, I've managed to find a different way to detect zoom factor.

Thank you again, the issue is resolved for us

**Comment by soommy12** [comment]
Thanks for the additional information, really appreciate that. We will put a note in the readme, that's for sure.
