### ISSUE TITLE
Highcharts don't work with dagger-hilt ! Help please

### ISSUE THREAD

**Issue by ismailtosun** [highcharts/highcharts-android#164]

**Comment by soommy12** [comment]
Hi @ismailtosun ! This issue was already mentioned in https://github.com/highcharts/highcharts-android/issues/153 where you can find any further follow-up information. As we mentioned there, this is out of the scope at this moment. If you have any useful stack-trace or ideas on how to improve on that specific matter we will definitely appreciate that!

**Comment by ismailtosun** [comment]
I found a solution to adding highchart as a subView of relativelayout
