### ISSUE TITLE
Custom Tooltip

### ISSUE THREAD

**Issue by nivCoindash** [highcharts/highcharts-android#19]
Hey, im trying to customise the tooltip in two ways.

1) try to add margin between tooltip and the marker by "setPositioner" but cants get the "point" - 
` HighChartsHelper.format(new HIFunctionInterface<HIChartContext, HashMap<String, Object>>() {
            @Override
            public HashMap<String, Object> apply(HIChartContext hiChartContext) {
              HashMap<String, Object> map = new 
              map.put("x", 0);
              return map;
            }
        }, "point)`

when debugging the HIChartContext the "point" is null.

2) how can i set fully custom text? (different font, color, 2 lines)

Thank you for your help!

Best regards, Niv

**Comment by soommy12** [comment]
Hi @nivCoindash ! Thanks for the question.
When it comes to positioner Highcharts Android you should use pure JS as `HIFunction` parameter because the wrapper doesn't support returning complex structures (like maps) in injected functions. I have prepared a simple example which answers to your questions. Here, take a look at this:
```
        HITooltip tooltip = new HITooltip();
        //general formatting
        tooltip.setBorderWidth(0);
        tooltip.setShadow(false);
        tooltip.setBorderColor(HIColor.initWithName("white"));
        //position of the tooltip
        tooltip.setPositioner(new HIFunction("function () { return { x: 100, y: 100 }; }"));
        //styling
        HIStyle tooltipStyle = new HIStyle();
        tooltipStyle.setFontFamily("serif");
        tooltipStyle.setColor("red");
        tooltip.setStyle(tooltipStyle);
        //text formatting, two lines
        tooltip.setFormatter(new HIFunction(f -> {
            String txt = f.getProperty("series.name") + "<br>" + "Value: " + f.getProperty("x");
            return txt;
        }, new String[] {"series.name", "x"}));
        options.setTooltip(tooltip);
```
**Ad. 2** if you want to know which values are accepted as editable in custom formatters by Highcharts library feel free to check those in the documentation in [here](https://api.highcharts.com/highcharts/tooltip.formatter)

**Comment by adirahman** [comment]
Hi @soommy12 , i want ti custom tooltip, the function of JS
tooltip: {
        formatter: function () {
            var s = '<b>' + this.x + '</b>'

            $.each(this.points, function () {
                s += '<br/>' + this.series.name + ': ' +
                    this.y + 'm'
            });

            return s;
        },
        shared: true
    }

but when i implemented on android it cannot be run
tooltip.setFormatter(new HIFunction("function () {\n" +
                "            var s = '<b>' + this.x + '</b>';\n" +
                "\n" +
                "            $.each(this.points, function () {\n" +
                "                s += '<br/>' + this.series.name + ': ' +\n" +
                "                    this.y + 'm';\n" +
                "            });\n" +
                "\n" +
                "            return s;\n" +
                "        }"));

**Comment by soommy12** [comment]
@adirahman hi there! If you copy-paste a JavaScript function please remove any unnecessary characters like `\n`

**Comment by nivCoindash** [comment]
@soommy12 Thank you for your help!

**Comment by soommy12** [comment]
According to [core Highcharts doc ](https://api.highcharts.com/highcharts/tooltip.pointFormat) you can create your own callback with the reference point position. Due to technical limitations this call can be done only in pure Javascript. As you can pass Javascript function in String, this is still possible in our native library:
`tooltip.setPositioner(new HIFunction("function (labelWidth, labelHeight, point) { var tX = point.plotX + 10; var tY = point.plotY - 10; return { x: tX, y: tY }; }"));`
You can change **10** value to whatever you want.

**Comment by mc-venkataramanaj** [comment]
@soommy12 

How to display the tooltip with new Array list value other than x and y axis in Android high charts bar graph

I have shared the full information in the below question
https://github.com/highcharts/highcharts-android/issues/306
