### ISSUE TITLE
How to know the series name when user click on Drilldown view

### ISSUE THREAD

**Issue by dnvsivaprasad** [highcharts/highcharts-android#220]
I want to do some native operation with series name clicked by user in drilldown with pie chart. i am getting null.

 options.chart.events.drilldown = HIFunction(
                HIConsumer { f: HIChartContext ->
                    Log.i(javaClass.canonicalName, "setProductData: "+f.getProperty("xaxis.x"))
                }, arrayOf("xaxis.x", "y")
            )

i am using above snippet but it returns null

**Comment by soommy12** [comment]
Hi @dnvsivaprasad ! It was already mentioned here https://github.com/highcharts/highcharts-android/issues/114 . Unfortuntelly we do not support callbacks with event objects values on mobile wrappers. I was looking for some trick solution but all I can propose is using this property strucutre: `f.getProperty("series.0.data.0.name")` where the second zero is an index of data in the series although. It's only static though, you cannot get a clicked index dynamically here which is required for your needs. 

There is also second solution, where you'll make use of series point click event instead of drilldown events:
```
val plotoptions = HIPlotOptions()
plotoptions.series = HISeries()
plotoptions.series.events = HIEvents()
plotoptions.series.point = HIPoint()
plotoptions.series.point.events = HIEvents()
plotoptions.series.point.events.click = HIFunction(
    HIConsumer { f: HIChartContext ->
        val t = Toast.makeText(this, "category: " + f.getProperty("category"), Toast.LENGTH_SHORT)
        t.show()
    }, arrayOf("x", "category"))
options.plotOptions = plotoptions
```
but it won't work since it's bugged for serie which is using drilldown in the core library and will also return null.

**Comment by MikolajMichalczak** [comment]
Hi @dnvsivaprasad,

I'm happy to inform you that starting from the latest version (11.4.7), it is now possible to access the series name when a user clicks on a drilldown view. You can achieve this using the following code:

```kotlin
val event = HIEvents()
event.drilldown = HIFunction(HIConsumer { f: HIChartContext ->
    val seriesName = f.getProperty("point.name")
}, arrayOf("point.name"))
chart.events = event
```

Since this feature is now implemented, I am closing this issue. If you have any further questions or feedback, please feel free to reopen the ticket.

**Comment by meirinberg** [comment]
@MikolajMichalczak Is it possible to obtain user-defined variables in the Highcharts Android event callbacks? In my iOS version, I use "custom" point properties. I can either nest them within the "custom" HIData property, or specify them directly in the point structure (x: 2.0, y: 1.0, IDs: "123XYZ, 987ABC, ..."). I've been able to return x, y, and other chart-related properties on Android -- but never my custom ones. Furthermore, I can access my user-defined properties in the tooltip, but they aren't exposed in any event callback. -- Posted full question here [https://github.com/highcharts/highcharts-android/issues/310](https://github.com/highcharts/highcharts-android/issues/310)
