### ISSUE TITLE
Is that possible to provide constants variable

### ISSUE THREAD

**Issue by royorange** [highcharts/highcharts-android#46]
Hi,
I found that some method like setZoomType, setLayout, setAlign, all these methods need a string
variable as param. 

For those specified string, is that possible to provide the constant in their class?(Like HILegend.LAYOUT_VERTICAL, etc.)

Thanks.

**Comment by sebastianbochan** [comment]
Hi @royorange ,
Due to the christmas time it will take some time until we are able to look into a solution.
Thank you for your patience.

**Comment by soommy12** [comment]
Hello @royorange ! Thanks for your suggestion. At this moment due to core library conversion to mobile, it's not possible. However, we will take it to our consideration in future releases.

**Comment by royorange** [comment]
Hi @soommy12 ,
thanks for your reply.
Got the point, and hope it more friendly for mobile use :)

**Comment by MikolajMichalczak** [comment]
Hi everyone,

I'm pleased to inform you that the requested feature is now available in the latest version (11.4.7). We have introduced constants for various configuration options, making it easier to use with specific functions.

Thank you for your patience, and we hope this enhancement will improve your experience.

Since this feature is now implemented, I am closing this issue. If you have any further questions or feedback, please feel free to reopen the ticket.
