### ISSUE TITLE
Loading indicator doesnt display

### ISSUE THREAD

**Issue by Geowan** [highcharts/highcharts-android#52]
Am trying to show a loading indicator on the graph via

                   
        HILoading hiLoading = new HILoading();
        hiLoading.setShowDuration(100);
        hiLoading.setHideDuration(2000);
        options.setLoading(hiLoading); 
       chartView.setOptions(options);

But the above doesnt show the loading indicator
I expect this to show loading after 100 milisecond and hide after2 seconds(2000)

Where am i going wrong?

**Comment by soommy12** [comment]
According to [documentation](https://api.highcharts.com/highcharts/loading): this screen only appears after an explicit call to `chart.showLoading()` (function called in Javascript). 
In other words: setting those options lets you use `showLoading()` later in your code. Keep in mind that `setShowDuration` and `setHideDuration` apply only for loading screen animation time. Another important thing is that when it comes to android wrapper you should use `this.showLoading()` instead of `chart.showLoading()` in `HIFunction`'s because our `HIChartView` is representing one chart.

**Comment by Geowan** [comment]
@soommy12  Could you clarify on where i should call the HIFunction, Checking on chart object. doesnt have an option to add a HIFunction, probably an example

Regards

**Comment by soommy12** [comment]
Yes, sure. Depending what you want to achieve. Let's say you want it on the chart load. Then you should do it like this:
```
HIChart chart = new HIChart();
chart.setEvents(new HIEvents());
chart.getEvents().setLoad(new HIFunction("function() { this.showLoading(); }"));
options.setChart(chart);
```
Ofcourse, that's only showing the loading screen. Feel free to edit the `HIFunction` content. Also, remamber that you can use `this.showLoading()` wherever you can pass `HIFunction` object.

**Comment by Geowan** [comment]
Thanks i see the the events now works

**Comment by bitfield66** [comment]
Hi,

how to dismiss the loader after completion of rendering?
