### ISSUE TITLE
Tooltip does not disappear after touch gesture is finished

### ISSUE THREAD

**Issue by adenisyuk** [highcharts/highcharts-android#79]
`Highcharts Android v7.0.3`

Tooltip continues to be visible even when user started to interact with different app views.
That said, the only ways to hide the tooltip now are 
-- zoom in/out
-- pan the chart

Reproducible in your demo app as well

**Comment by soommy12** [comment]
Yes, we are aware of that. This happens because the embedded chart doesn't know if the gesture is actually finished. The chart itself has no idea about what is happening outside of it. Treat it like a box which freezes it state when you leave it. It's not an accurate comparison but gives a general idea of why this problem occurs. It's all about the communication between native Javascript library with the Android wrapper. There are many features which have higher priority than this but I will look into it also. Thanks for the question! :)

**Comment by adenisyuk** [comment]
What about handling the focus lost event on a WebView and propagating it to the internal JS Chart?

**Comment by soommy12** [comment]
This is what we are currently testing.

**Comment by soommy12** [comment]
@adenisyuk the problem with chart freezing after losing focus is solved and will be introduced in the next release
