### ISSUE TITLE
How to set setDistance DataLabel for PieChart.

### ISSUE THREAD

**Issue by hienrk** [highcharts/highcharts-android#91]
Hi team,
I use this code line plotOptions.getPie().getDataLabels().setDistance(-50) in my project.
But when I update version from 7.0.3 to 7.1.1 it not working.
Could you tell me corresponding method in 7.1.1 version?
Thank you very much.

**Comment by soommy12** [comment]
Hello @hienrk ! First of all, sorry for your waiting and the inconvenience, I was on holiday. The options you mentioned are not available indeed. That's because now there is a separate class for pie data labels `HIPlotPieDataLabelsOptionsObject`. The actual problem is that the method `setDataLabels` doesn't allow to pass this kind of object as the parameter. In the core library, this class extends `HIDataLabelsOptionsObject` but they didn't link those classes before 7.1.1 release. I have contacted Javascript developer, this is already fixed on their side. We will introduce the fix in the next release. Stay tuned!

**Comment by zhy1stgg** [comment]
Hi @soommy12 , I can't find `HIPlotPieDataLabelsOptionsObject` Class in 7.2.1, so I do't know how to chang `datalabels.distance` in pie

> Hello @hienrk ! First of all, sorry for your waiting and the inconvenience, I was on holiday. The options you mentioned are not available indeed. That's because now there is a separate class for pie data labels `HIPlotPieDataLabelsOptionsObject`. The actual problem is that the method `setDataLabels` doesn't allow to pass this kind of object as the parameter. In the core library, this class extends `HIDataLabelsOptionsObject` but they didn't link those classes before 7.1.1 release. I have contacted Javascript developer, this is already fixed on their side. We will introduce the fix in the next release. Stay tuned!

**Comment by soommy12** [comment]
Hi @zhy1stgg ! As I said in the previous post, there is no such class. You should use `HIDataLabelsOptionsObject` which currently doesn't have `distance` field as a parameter. This is a small bug which comes from the core library but it is already fixed in the newest update (8.0) which will be here just before Christmas. Stay tuned!
